var wordMaps={
		"你的名字": "Your Name",
		"一句话介绍自己，告诉HR为什么选择你而不是别人": "Please Enter a summary",
		"年龄": "Birthday",
		"所在城市": "City",
		"工作年限": "Service Year",
		"联系电话": "Mobile",
		"电子邮箱": "Email",
		"性别":"Sex",
		"民族":"Nation",
		"学历":"Education",
		"婚姻":"Marital",
		"面貌":"Political",
		"城市":"City",
		"基本信息": "Information",
		"个人主页": "Home",
		"社交账号": "Social account",
		"求职意向": "JOB PREFERENCES",
		"意向岗位": "Function",
		"职业类型": "Job Type",
		"意向城市": "Location",
		"薪资要求": "Target Salary",
		"入职时间": "Duty Time",
		"头像": "Head",
		"自荐信": "LETTER",
		"封面": "COVER",
		"教育背景": "EDUCATION",
		"工作经验": "WORK EXPERIENCE",
		"校园活动": "CAMPUS ACTIVITIES",
		"实习经验": "INTERNSHIP EXPERIENCE",
		"志愿者经历": "VOLUNTEER EXPERIENCE",
		"项目经验": "PROJECT EXPERIENCE",
		"荣誉奖项": "HONORS & AWARDS",
		"技能特长": "SKILLS",
		"添加技能特长": "Add skills",
		"兴趣爱好": "INTERESTS",
		"添加兴趣爱好": "Add interests",
		"作品展示": "Portfolio",
		"添加作品": "Add portfolio items",
		"自我评价": "SUMMARY",
		"二维码": "QR CODE",
		"感谢您的阅读，扫一扫查看我的手机简历": "please scan my resume",
		"添加自定义模块": "add new templates",
		"初中及以下": "Junior High and Below",
		"高中": "High School",
		"中技": "Technical School",
		"中专": "Polytechnic",
		"大专": "Associate",
		"本科": "Bachelor",
		"硕士": "Master",
		"博士": "Doctorate",
		"应届生": "graduate",
		"1年经验": "1year experience",
		"2年经验": "2years experience",
		"3年经验": "3years experience",
		"4年经验": "4years experience",
		"5年经验": "5years experience",
		"6年经验": "6years experience",
		"7年经验": "7years experience",
		"8年经验": "8years experience",
		"9年经验": "9years experience",
		"10年经验": "10years experience",
		"10年以上经验": "More than 10 years experience",
		"男": "Male",
		"女": "Female",
		"未婚": "Unmarried",
		"已婚": "Married",
		"保密": "Private",
		"中共党员": "Party Member",
		"中共预备党员": "Probationary Party",
		"共青团员": "League Member",
		"民主党派人士": "Democratic Party",
		"无党派民主人士": "No Party",
		"普通公民": "Citizen",
		"全职": "Full-time",
		"兼职": "Part-time",
		"实习": "Intern/Trainee",
		"随时到岗": "immediately",
		"一周内到岗": "within 1 week",
		"一个月内到岗": "within 1 month",
		"三个月内到岗": "within 3 month",
		"到岗时间另议": "to be determined",
		"一般": "Average",
		"良好": "Good",
		"熟练": "Advanced",
		"精通": "Expert",
		"元/日": "RMB/day",
		"设置时间": "Time period",
		"填写学校名称": "School name",
		"填写专业名称": "Major...",
		"描述": "Description...",
		"填写公司名称": "Organization...",
		"填写职位名称": "Job title...",
		"填写项目名称": "Project name",
		"填写角色名称": "Role name",
		"报考信息":"REGISTER FOR AN EXAMINATION",
		"填写报考学校":"School name",
		"填写报考专业":"Major...",
		"填写课程":"Course",
		"填写成绩":"Score",
}